#!/usr/bin/env python3
"""
Setup script for Codeforces Submission Fetcher
Helps users set up their configuration file
"""

import os
import shutil

def setup_config():
    """Setup configuration file for the user."""
    print("=== Codeforces Submission Fetcher Setup ===\n")
    
    if os.path.exists("config.py"):
        print("⚠️  config.py already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    print("Let's set up your Codeforces API credentials.")
    print("You can get your API key and secret from: https://codeforces.com/settings/api\n")
    
    handle = input("Enter your Codeforces handle: ").strip()
    api_key = input("Enter your API key: ").strip()
    api_secret = input("Enter your API secret: ").strip()
    
    config_content = f'''# Codeforces Submission Fetcher Configuration
# Generated by setup script

# Your Codeforces credentials
HANDLE = "{handle}"
API_KEY = "{api_key}"
API_SECRET = "{api_secret}"

# Directory settings (you can modify these if needed)
SAVE_DIR = "submissions"
JSON_FILE = "codeforces_submissions.json"
README_FILE = "README.md"
'''
    
    try:
        with open("config.py", "w", encoding="utf-8") as f:
            f.write(config_content)
        print("\n✅ Configuration saved to config.py")
        print("🔒 Remember: Never commit config.py to version control!")
        print("📝 You can now run: python CF_FETCH.py")
    except Exception as e:
        print(f"❌ Error creating config file: {e}")

if __name__ == "__main__":
    setup_config()
